[2025-07-09T07:58:20.570+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T07:58:20.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_airflare_data.extract manual__2025-07-09T07:58:17.397989+00:00 map_index=9 [queued]>
[2025-07-09T07:58:20.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_airflare_data.extract manual__2025-07-09T07:58:17.397989+00:00 map_index=9 [queued]>
[2025-07-09T07:58:20.605+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-09T07:58:20.624+0000] {taskinstance.py:2330} INFO - Executing <Mapped(_PythonDecoratedOperator): extract> on 2025-07-09 07:58:17.397989+00:00
[2025-07-09T07:58:20.638+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7144) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-09T07:58:20.641+0000] {standard_task_runner.py:63} INFO - Started process 7177 to run task
[2025-07-09T07:58:20.640+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_airflare_data', 'extract', 'manual__2025-07-09T07:58:17.397989+00:00', '--job-id', '613', '--raw', '--subdir', 'DAGS_FOLDER/Untitled-1.py', '--cfg-path', '/tmp/tmp812bcnm5', '--map-index', '9']
[2025-07-09T07:58:20.645+0000] {standard_task_runner.py:91} INFO - Job 613: Subtask extract
[2025-07-09T07:58:20.738+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_airflare_data.extract manual__2025-07-09T07:58:17.397989+00:00 map_index=9 [running]> on host e6a32b72ede0
[2025-07-09T07:58:20.883+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_airflare_data' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T07:58:17.397989+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T07:58:17.397989+00:00'
[2025-07-09T07:58:20.886+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T07:58:20.887+0000] {Untitled-1.py:134} INFO - Начало извлечения данных для направления VVO-IKT
[2025-07-09T07:58:21.707+0000] {Untitled-1.py:59} INFO - Создание подключения к S3
[2025-07-09T07:58:21.709+0000] {Untitled-1.py:62} INFO - Подключение установлено
[2025-07-09T07:58:21.723+0000] {base.py:84} INFO - Using connection ID 'minio' for task execution.
[2025-07-09T07:58:21.724+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='minio', conn_type='aws') credentials retrieved from login and password.
[2025-07-09T07:58:22.243+0000] {Untitled-1.py:68} INFO - Загрузка данных в S3
[2025-07-09T07:58:22.694+0000] {Untitled-1.py:79} INFO - Загрузка завершена успешно
[2025-07-09T07:58:22.699+0000] {Untitled-1.py:147} INFO - Данные успешно сохранены во временное хранилище
[2025-07-09T07:58:22.699+0000] {Untitled-1.py:148} INFO - Данные успешно извлечены и переданы в Xcom
[2025-07-09T07:58:22.704+0000] {python.py:237} INFO - Done. Returned value was: {'path': {'bucket': 'airflare', 'key': 'temp/response_VVO_IKT.json'}, 'rout': {'origin': 'VVO', 'destination': 'IKT', 'bd': 'Владивосток_Иркутск_return'}}
[2025-07-09T07:58:22.706+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T07:58:22.755+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_airflare_data, task_id=extract, run_id=manual__2025-07-09T07:58:17.397989+00:00, map_index=9, execution_date=20250709T075817, start_date=20250709T075820, end_date=20250709T075822
[2025-07-09T07:58:22.876+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-09T07:58:22.897+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
